# Generated by Django 5.2.7 on 2025-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_description_alter_video_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link da miniatura (opcional)'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do vídeo (opcional)'),
        ),
    ]
