# Generated by Django 5.1.3 on 2025-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_video_thumbnail_url_video_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="video",
            name="subject",
            field=models.CharField(max_length=100, verbose_name="Matéria"),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Arquivo da miniatura ",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                verbose_name="Arquivo da vídeo ",
            ),
        ),
    ]
