# Generated by Django 5.2.7 on 2025-11-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=10, verbose_name='Tipo de usuário'),
        ),
    ]
